version: '3.9'

networks:
    calendarweb:

services:
  mssqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=cALendardbpa$$word1
    ports:
        - 1433:1433

  calendarnet:
    image: ${DOCKER_REGISTRY-}calendarnet
    build:
        context: .
        dockerfile: CalendarNET/Dockerfile
    ports:
        - 5000:80
    depends_on:
        - mssqldb
    environment:
        - DB_HOST=mssqldb
        - DB_SA_PASSWORD=cALendardbpa$$word1
        - DB_NAME=calendar
        - SECRET_KEY=!MY_very_secret_key_for_JWT!


  